# Generated by Django 5.0.4 on 2024-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descriptionEN',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='descriptionSP',
            field=models.TextField(default=None),
        ),
    ]
