# Generated by Django 5.0.4 on 2024-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_technologies_project_screen1_project_screen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.technologies'),
        ),
    ]
