# Generated by Django 5.0.4 on 2024-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_appstoreurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('image', models.ImageField(blank=True, default=None, upload_to='portfolio/images/profiles')),
                ('linkedinUrl', models.CharField(blank=True, default=None, max_length=255)),
                ('githubUrl', models.CharField(blank=True, default=None, max_length=255)),
                ('email', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
    ]
