# Generated by Django 5.0.4 on 2024-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descriptionEN',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='descriptionSP',
            field=models.TextField(blank=True, default=None),
        ),
    ]
