# Generated by Django 5.0.4 on 2024-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='portfolio/images/covers'),
        ),
    ]
