# Generated by Django 5.0.4 on 2024-05-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_project_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
    ]
